version: '2'

services:
  tmweb:
    image: httpd:alpine
    ports:
      - "127.0.0.1:8888:80"
    depends_on:
      - tmapp
    volumes:
      - "./transmart-web/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf"
      - "./transmart-web/httpd.conf:/usr/local/apache2/conf/httpd.conf"
  tmapp:
    image: dennyverbeeck/transmart-app:etriks-v3.0
    ports:
      - "127.0.0.1:8009:8009"
    depends_on:
      - tmdb
      - tmsolr
    volumes:
      - "./transmart-app/Config.groovy:/root/.grails/transmartConfig/Config.groovy"
      - "./transmart-app/DataSource.groovy:/root/.grails/transmartConfig/DataSource.groovy"
      - "./transmart-app/setenv.sh:/usr/local/tomcat/bin/setenv.sh"
      - "appdata:/root/.grails"
      - "apptmp:/tmp"
      - "appwebapps:/usr/local/tomcat/webapps"
  tmdb:
    image: dennyverbeeck/transmart-db:etriks-v3.0
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "postgresdata:/var/lib/postgresql"
      - "postgreslogs:/var/log/postgresql"
  tmsolr:
    image: dennyverbeeck/transmart-solr:etriks-v3.0
  tmrserve:
    image: dennyverbeeck/transmart-rserve:etriks-v3.0
    volumes:
      - "apptmp:/tmp"
      - "appwebapps:/usr/local/tomcat/webapps"
  tmload:
    image: dennyverbeeck/transmart-load:etriks-v3.0
    depends_on:
      - tmdb

volumes:
  appdata:
  apptmp:
  appwebapps:
  postgresdata:
  postgreslogs:
